export const repoInfoMockData = {
  id: 10270250,
  node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
  name: 'react',
  full_name: 'facebook/react',
  private: false,
  html_url: 'https://github.com/facebook/react',
  description: 'The library for web and native user interfaces.',
  fork: false,
  url: 'https://api.github.com/repos/facebook/react',
  forks_url: 'https://api.github.com/repos/facebook/react/forks',
  keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
  collaborators_url:
    'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/facebook/react/teams',
  hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
  issue_events_url:
    'https://api.github.com/repos/facebook/react/issues/events{/number}',
  events_url: 'https://api.github.com/repos/facebook/react/events',
  assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
  branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
  tags_url: 'https://api.github.com/repos/facebook/react/tags',
  blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/facebook/react/languages',
  stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
  contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
  subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
  subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
  commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
  git_commits_url:
    'https://api.github.com/repos/facebook/react/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
  issue_comment_url:
    'https://api.github.com/repos/facebook/react/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
  compare_url:
    'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/facebook/react/merges',
  archive_url:
    'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
  issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
  pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
  milestones_url:
    'https://api.github.com/repos/facebook/react/milestones{/number}',
  notifications_url:
    'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
  releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
  deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
  created_at: '2013-05-24T16:15:54Z',
  updated_at: '2024-04-07T09:19:24Z',
  pushed_at: '2024-04-07T05:58:00Z',
  git_url: 'git://github.com/facebook/react.git',
  ssh_url: 'git@github.com:facebook/react.git',
  clone_url: 'https://github.com/facebook/react.git',
  svn_url: 'https://github.com/facebook/react',
  homepage: 'https://react.dev',
  size: 429455,
  stargazers_count: 421057,
  watchers_count: 221057,
  language: 'JavaScript',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: true,
  has_discussions: false,
  forks_count: 45148,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 1604,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: ['declarative', 'frontend', 'javascript', 'library', 'react', 'ui'],
  visibility: 'public',
  forks: 45148,
  open_issues: 1604,
  watchers: 221057,
  default_branch: 'main',
  temp_clone_token: null,
  custom_properties: {},
  network_count: 45148,
  subscribers_count: 6622,
};

export const responseData = [
  {
    html_url: 'https://github.com/test/testsss/test',
    id: 2229367850,
    number: 3,
    title: 'Test',
    state: 'open',
    assignee: null,
    assignees: [],
    comments: 0,
    created_at: '2024-04-06T19:04:39Z',
    updated_at: '2024-04-06T19:04:39Z',
    closed_at: null,
  },
];
